/* Account investigation and recovery workspace; explicitly rule-based until AI is connected. */
(()=>{'use strict';
const W=window.PulseWorkspace,I=window.PulseInvestigator,e=W.escapeHTML,$=s=>document.querySelector(s);
let selected='',records=Object.create(null),active=false;
const styles=document.createElement('link');styles.rel='stylesheet';styles.href='copilot.css';document.head.append(styles);
const nav=document.createElement('button');nav.textContent='✧ Account investigation';nav.id='investigate-nav';$('nav[aria-label="Main navigation"]').insertBefore(nav,$('[data-view="playbook"]'));
const section=document.createElement('section');section.id='copilot';section.hidden=true;section.innerHTML=`<div class="agent-status"><div><b>Investigation workspace</b><span>Rule-based analysis · no AI model connected</span></div><div class="button-group"><button class="button small" id="recovery-export">Export recovery records</button><label class="button small restore-label">Restore records<input id="recovery-import" type="file" accept=".json,application/json"></label></div></div><p class="small-note">Records stay in this tab. Export before closing. No messages are sent and no external account is changed.</p><div class="agent-layout"><aside class="agent-accounts"><label>Find an account<input id="agent-search" type="search" placeholder="Search accounts…"></label><div id="agent-account-list"></div></aside><div id="agent-brief" aria-live="polite"></div></div>`;
$('main').insertBefore(section,$('footer'));
const key=a=>JSON.stringify([a.customer_id,a.name]);
const record=a=>records[key(a)]??={customer_id:a.customer_id,name:a.name,notes:[],plan:null,history:[]};
function current(){const {data,config}=W.read();if(!data.accounts.some(a=>a.customer_id===selected))selected=Pulse.ranked(data,config)[0]?.customer_id||'';const a=data.accounts.find(a=>a.customer_id===selected);return a?{...W.read(),a,rec:record(a)}:null;}
function open(){active=true;$('.page-heading').hidden=true;$('#metrics').hidden=true;document.querySelectorAll('.view').forEach(x=>x.hidden=true);document.querySelectorAll('[data-view]').forEach(x=>x.classList.remove('active'));nav.classList.add('active');$('#view-label').textContent='Account investigation';section.hidden=false;render();}
nav.onclick=open;
document.addEventListener('click',ev=>{if(ev.target.closest('[data-view]')){active=false;section.hidden=true;$('.page-heading').hidden=false;nav.classList.remove('active');}});
function list(){const {data,config}=W.read(),search=$('#agent-search').value.toLowerCase();$('#agent-account-list').innerHTML=Pulse.ranked(data,config).filter(a=>(a.name+' '+a.owner).toLowerCase().includes(search)).map(a=>`<button data-investigate="${e(a.customer_id)}" class="account-pick ${selected===a.customer_id?'selected':''}"><b>${e(a.name)}</b><span>${e(a.status)} · ${e(a.owner||'Unassigned')}</span></button>`).join('')||'<p>No matching accounts.</p>';}
function render(){const c=current();if(!c)return;list();const {data,config,a,rec}=c,b=I.investigate(data,a.customer_id,config,rec.notes),r=b.account,plan=rec.plan,review=plan?I.review(plan,b):null;
$('#agent-brief').innerHTML=`<article class="investigation-card"><div class="brief-head"><div><span class="eyebrow">ACCOUNT INVESTIGATION</span><h2>${e(a.name)}</h2><p>${e(a.owner||'Unassigned')} · Snapshot ${e(data.asOf)}</p></div><span class="pill ${Pulse.STATUS_CLASS[r.status]}">${e(r.status)}</span></div><div class="agent-kpis"><div><span>Monthly value</span><b>${e(new Intl.NumberFormat('en-US',{style:'currency',currency:config.currency,maximumFractionDigits:0}).format(r.monthly_value))}</b></div><div><span>Decision window</span><b>${r.renewal===null?'Not supplied':r.renewal<0?'Renewal date passed':e(r.renewal)+' days'}</b></div><div><span>Evidence coverage</span><b>${e(b.confidence)}</b></div></div><h3>What is failing</h3>${b.facts.length?b.facts.map(f=>`<div class="agent-evidence"><b>${e(f.label)}</b><p>${e(f.detail)}</p><small>${e(f.source)}${f.fresh?'':' · verify freshness'}</small></div>`).join(''):'<p>No rule has flagged a problem in the available records. Confirm the customer’s success outcomes before concluding that the relationship is healthy.</p>'}<h3>Possible causes to validate</h3>${b.hypotheses.map(h=>`<div class="hypothesis"><b>Hypothesis · unconfirmed</b><p>${e(h.text)}</p><p><b>Ask:</b> ${e(h.question)}</p><small>Based on: ${e(h.evidence.join(', '))}</small></div>`).join('')||'<p>No causal hypothesis suggested for this lifecycle or available evidence.</p>'}<details><summary>Unknowns and limitations</summary><ul>${b.unknowns.map(x=>`<li>${e(x)}</li>`).join('')}</ul><p>Signals are not churn probabilities. Seasonality and non-additive service units require human interpretation. Notes are retained as evidence but are not interpreted by an AI model.</p></details><button class="button small" id="open-source">Open underlying account data</button></article>
<article class="investigation-card"><h3>Customer context</h3><p>Add feedback, meeting observations or explanations with a date and source. Keep hypotheses separate from reported statements.</p><div class="context-notes">${rec.notes.map(n=>`<div class="agent-evidence"><b>${e(n.kind)} · ${e(n.date)}</b><p>${e(n.text)}</p><small>${e(n.source)}</small></div>`).join('')||'<p class="small-note">No context added yet.</p>'}</div><form id="context-form"><div class="form-grid"><label>Evidence type<select name="kind"><option value="customer report">Customer report</option><option value="observation">Observation</option><option value="hypothesis">Hypothesis</option></select></label><label>Evidence date<input type="date" name="date" value="${e(data.asOf)}" max="${e(data.asOf)}" required></label></div><label>Source or reference<input name="source" maxlength="200" placeholder="Meeting note, ticket reference, or conversation" required></label><label>What happened<textarea name="text" maxlength="2000" required placeholder="Record the evidence, not a conclusion without support."></textarea></label><button class="button" type="submit">Add context</button></form></article>
<article class="investigation-card"><div class="brief-head"><div><h3>${plan?'Recovery plan':'Recommended next actions'}</h3><p>Due dates start from the displayed snapshot, not today. Adjust them before assigning work.</p></div><button class="button dark" id="create-recovery">${plan?'Refresh proposed actions':'Create recovery plan'}</button></div>${plan?`<div class="review-callout"><b>${e(review.status)}</b><p>${e(review.text)}</p><small>Baseline captured ${e(plan.baseline.snapshot)} · review date ${e(plan.reviewDate)}</small></div><label>Next review date<input id="review-date" type="date" value="${e(plan.reviewDate)}"></label>`:''}<div>${(plan?plan.tasks:b.tasks).map((t,i)=>`<div class="recovery-task"><div class="task-heading"><span class="task-number">${i+1}</span><b>${e(t.title)}</b></div><p class="small-note">Reason: ${e(t.reason)}</p>${plan?`<div class="task-fields"><label>Responsible owner<input data-task="${e(t.id)}" data-field="owner" maxlength="80" value="${e(t.owner)}"></label><label>Due date<input data-task="${e(t.id)}" data-field="due" type="date" value="${e(t.due)}"></label><label>Task status<select data-task="${e(t.id)}" data-field="status">${['Proposed','Approved','In progress','Done','Blocked'].map(s=>`<option${s===t.status?' selected':''}>${s}</option>`).join('')}</select></label></div>`:`<p>${e(t.owner)} · due ${e(t.due)}</p>`}<p><b>Success:</b> ${e(t.success)}</p><p><b>Escalate if:</b> ${e(t.trigger)}</p>${plan?`<label>Outcome evidence<textarea data-task="${e(t.id)}" data-field="outcome" maxlength="1000" placeholder="What changed? Add a date or source.">${e(t.outcome||'')}</textarea></label>`:''}</div>`).join('')}</div>${plan?'<button class="button dark" id="save-recovery">Save plan changes</button><p class="small-note">Approval records your decision only. It does not send a message, assign work in another tool, or declare recovery.</p>':''}</article>
<article class="investigation-card"><h3>Customer outreach draft</h3><p>Review the facts and commitments before sending this yourself.</p><textarea id="outreach-draft" rows="7" aria-label="Customer outreach draft">${e(`Hi,\n\nI’d like to review our work together. ${a.lifecycle==='paused'?'I’d like to confirm our agreed restart date and conditions.':a.lifecycle==='onboarding'?'I’d like to agree your first value milestone and resolve any activation blockers.':b.facts.length?`Our records flag: ${b.facts.slice(0,2).map(f=>f.label.toLowerCase()).join('; ')}.`:'I’d like to confirm your next success milestone.'} Could we confirm whether this matches your experience and discuss any changes in demand or priorities?\n\nI suggest we agree the next milestone, an accountable owner and a review date. Please let me know who should join that conversation.\n\n${a.owner||'Your customer success team'}`)}</textarea><button class="button small" id="copy-outreach">Copy draft</button><h3>Plan history</h3>${rec.history.slice(-8).reverse().map(h=>`<p class="small-note">${e(h.at)} · ${e(h.text)}</p>`).join('')||'<p class="small-note">No recovery plan changes yet.</p>'}</article>`;
$('#open-source').onclick=()=>W.openCustomer(selected);
$('#context-form').onsubmit=ev=>{ev.preventDefault();const f=new FormData(ev.currentTarget),n=Object.fromEntries(f);if(!Pulse.dateValue(n.date)||n.date>data.asOf||!n.source.trim()||!n.text.trim())return W.toast('Enter dated evidence and a source.');if(rec.notes.length>=100)return W.toast('Maximum 100 context records per account.');rec.notes.push(n);render();};
$('#create-recovery').onclick=()=>{if(!rec.plan)rec.plan={baseline:b.baseline,reviewDate:new Date(Date.parse(data.asOf)+7*86400000).toISOString().slice(0,10),tasks:b.tasks};else{const ids=new Set(rec.plan.tasks.map(t=>t.id));rec.plan.tasks.push(...b.tasks.filter(t=>!ids.has(t.id)));}rec.history.push({at:new Date().toISOString(),text:plan?'Added newly recommended actions; existing work preserved.':'Recovery plan created from snapshot '+data.asOf});render();};
if(plan)$('#save-recovery').onclick=()=>{const tasks=plan.tasks.map(t=>({...t}));for(const input of section.querySelectorAll('[data-task]')){const t=tasks.find(t=>t.id===input.dataset.task);t[input.dataset.field]=input.value.trim();}const reviewDate=$('#review-date').value;if(!Pulse.dateValue(reviewDate)||tasks.some(t=>!t.owner||!Pulse.dateValue(t.due)))return W.toast('Every task needs an owner and valid due date.');if(tasks.some(t=>t.status==='Done'&&!t.outcome))return W.toast('Add outcome evidence before marking a task Done.');plan.tasks=tasks;plan.reviewDate=reviewDate;rec.history.push({at:new Date().toISOString(),text:'Plan saved: '+tasks.filter(t=>t.status==='Done').length+' of '+tasks.length+' tasks done. Recovery still requires validation.'});render();W.toast('Plan saved in this tab. Export to retain it.');};
$('#copy-outreach').onclick=async()=>{try{await navigator.clipboard.writeText($('#outreach-draft').value);W.toast('Draft copied. Review it before sending.');}catch{W.toast('Select the draft and copy it manually.');}};
}
$('#agent-search').oninput=list;
section.addEventListener('click',ev=>{const target=ev.target.closest('[data-investigate]');if(target){selected=target.dataset.investigate;render();}});
$('#recovery-export').onclick=()=>{const blob=new Blob([JSON.stringify({version:1,records:Object.values(records)},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='customer-pulse-recovery.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('#recovery-import').onchange=async ev=>{try{const file=ev.target.files[0];if(!file)return;if(file.size>2*1024*1024)throw Error('Recovery file must be smaller than 2 MB.');const payload=JSON.parse(await file.text());if(payload.version!==1||!Array.isArray(payload.records)||payload.records.length>500)throw Error('Unsupported recovery file.');const next=Object.create(null),string=(v,max)=>typeof v==='string'&&v.length<=max,baselineFields=['latest','baseline','score','on_time_pct','critical_issues','overdue_days'];for(const r of payload.records){if(!string(r.customer_id,64)||!string(r.name,100)||!Array.isArray(r.notes)||r.notes.length>100||!Array.isArray(r.history)||r.history.length>1000)throw Error('Invalid account recovery record.');if(r.notes.some(n=>!['customer report','observation','hypothesis'].includes(n.kind)||!Pulse.dateValue(n.date)||!string(n.source,200)||!string(n.text,2000)))throw Error('Invalid context record.');if(r.history.some(h=>!string(h.at,50)||!string(h.text,500)))throw Error('Invalid history record.');if(r.plan){const p=r.plan;if(!p.baseline||!Pulse.dateValue(p.baseline.snapshot)||!/^\d{4}-(0[1-9]|1[0-2])$/.test(p.baseline.closed)||!Pulse.dateValue(p.reviewDate)||!Array.isArray(p.tasks)||p.tasks.length>30||baselineFields.some(k=>p.baseline[k]!==null&&(!Number.isFinite(p.baseline[k])||p.baseline[k]<0)))throw Error('Invalid plan baseline.');const ids=new Set();for(const t of p.tasks){if(!string(t.id,100)||ids.has(t.id)||!string(t.title,500)||!string(t.owner,80)||!Pulse.dateValue(t.due)||!string(t.success,1000)||!string(t.trigger,1000)||!string(t.reason,2000)||!['Proposed','Approved','In progress','Done','Blocked'].includes(t.status)||t.status==='Done'&&(!string(t.outcome,1000)||!t.outcome.trim())||t.outcome!==undefined&&!string(t.outcome,1000))throw Error('Invalid plan task.');ids.add(t.id);}}if(next[key(r)])throw Error('Duplicate account recovery record.');next[key(r)]=r;}records=next;render();W.toast('Recovery records restored. Matching uses account ID and name.');}catch(err){W.toast(err.message);}ev.target.value='';};
// Refresh only when an import/settings dialog closes, preserving the original dashboard events.
for(const id of ['data-dialog','settings-dialog'])$('#'+id).addEventListener('close',()=>{if(active)open();});
})();
