const assert=require('node:assert/strict');
const P=require('./model.js'),d=P.demo(),c=P.DEFAULTS;
const list=P.ranked(d,c);
assert.equal(list.length,12);
assert.equal(list.find(r=>r.customer_id==='DEMO-Q7M').status,'Critical');
assert.equal(list.find(r=>r.customer_id==='DEMO-T9V').status,'At risk');
assert.equal(list.find(r=>r.customer_id==='DEMO-L1Y').status,'Review data');
assert.equal(list.find(r=>r.customer_id==='DEMO-K8S').status,'Review data');
assert.equal(list.find(r=>r.customer_id==='DEMO-D0R').status,'Onboarding');
assert.equal(list.find(r=>r.customer_id==='DEMO-F4C').status,'Paused');
assert(list.every(r=>r.score>=0&&r.score<=100));
const q=d.accounts[0];
const moreMTD=d.activity.map(r=>({...r,units:r.month==='2026-09'?r.units*100:r.units}));
assert.equal(P.evaluate(q,moreMTD,d.asOf,c).score,P.evaluate(q,d.activity,d.asOf,c).score,'Partial month never affects decline scoring');
const incomplete=d.activity.filter(r=>!(r.customer_id===q.customer_id&&r.month==='2026-07'&&r.service==='Advisory'));
assert.equal(P.evaluate(q,incomplete,d.asOf,c).status,'Review data','Incomplete service history must not be mistaken for decline');
const valid=P.validateImport(d.accounts,d.activity,d.asOf);assert.deepEqual(valid.errors,[]);
assert(P.validateImport([...d.accounts,d.accounts[0]],d.activity,d.asOf).errors.length);
assert(P.validateImport(d.accounts,[...d.activity,d.activity[0]],d.asOf).errors.length);
assert(P.validateImport(d.accounts,[{...d.activity[0],units:-1}],d.asOf).errors.length);
assert(P.validateImport(d.accounts,[{...d.activity[0],units:' '}],d.asOf).errors.length);
assert(P.validateImport(d.accounts,[{...d.activity[0],month:'2026-10'}],d.asOf).errors.length);
assert(P.validateImport(d.accounts,[{...d.activity[0],customer_id:'unknown'}],d.asOf).errors.length);
assert(P.validateImport(d.accounts,d.activity,'2026-02-30').errors.length);
const hostile={...d,accounts:[{...q,customer_id:'__proto__'}],activity:d.activity.filter(r=>r.customer_id===q.customer_id).map(r=>({...r,customer_id:'__proto__',service:r.service==='Advisory'?'constructor':r.service}))};
assert.equal(P.ranked(hostile,c).length,1);
console.log('17 risk, data-quality, import-validation and special-identifier checks passed.');
console.table(list.map(r=>({id:r.customer_id,status:r.status,score:r.score,change:Math.round(r.change||0)})));
